global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "stock_api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "celery_worker"
    static_configs:
      - targets: ["celery_worker:9090"]
